In [5]:
import pickle
import tensorflow as tf

### Deserielize numpy arrays associated to sentences-in

In [8]:
# Getting back the serielized numpy array:
def loadInData(serialized_in_arrays):
    with open(serialized_in_arrays, 'rb') as objs_in:  # Python 3: open(..., 'rb')
        x_in, y_in = pickle.load(objs_in)

    #print(x_in)
    #print(y_in)
    
    return x_in, y_in

In [11]:
def buildModel():
    X, Y = loadInData('bows.pkl')
    
    print (X)
    print (Y)
    

buildModel()

[[0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1]
 [0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]]
[[0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]]
